#!/bin/bash
for repo in $(cat /etc/git_pusher/repos_to_sync); do
  for remote in $(cat /etc/git_pusher/remotes); do
    cd $repo ; GIT_SSH=/etc/git-pusher/ssh_wrapper_${remote}_${repo} git push -f $remote
  done;
done;
